name: Update Homebrew Formula
on:
  release:
    types: [published]

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew-tap
        uses: actions/checkout@v4
        with:
          repository: zoetin45/homebrew-mdc
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}

      - name: Update Formula
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          
          # ファイル名とURLを構築
          DMG_NAME="mdc_${VERSION}_universal.dmg"
          DMG_URL="https://github.com/zoetin45/mdc/releases/download/${{ github.event.release.tag_name }}/${DMG_NAME}"
          
          # ダウンロードしてSHA256を計算
          curl -sL "${DMG_URL}" -o "${DMG_NAME}"
          SHA256=$(shasum -a 256 "${DMG_NAME}" | cut -d' ' -f1)
          
          # Formulaを書き換え
          cat > Formula/mdc.rb << EOF
class Mdc < Formula
  desc "MDC - Markdown Converter"
  homepage "https://github.com/zoetin45/mdc"
  version "${VERSION}"
  
  url "${DMG_URL}"
  sha256 "${SHA256}"

  def install
    app = "mdc.app"
    prefix.install Dir["*"]
    bin.install_symlink prefix/app/"Contents/MacOS/mdc"
  end
end
EOF

      - name: Commit and push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Update to version ${{ github.event.release.tag_name }}"
          git push
