name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:  # 手動実行を追加
    inputs:
      tag_name:
        description: 'Release tag (e.g., v0.1.10)'
        required: true
        default: 'v0.1.10'

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
          fi
          
      - name: Checkout homebrew-tap
        uses: actions/checkout@v4
        with:
          repository: zoetin45/homebrew-mdc
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          
      - name: Update Formula
        run: |
          # バージョンを取得
          VERSION="${{ steps.version.outputs.tag }}"
          VERSION="${VERSION#v}"
          
          # DMGファイルの情報
          DMG_NAME="mdc_${VERSION}_universal.dmg"
          DMG_URL="https://github.com/zoetin45/mdc/releases/download/${{ steps.version.outputs.tag }}/${DMG_NAME}"
          
          # DMGをダウンロード
          curl -sL "${DMG_URL}" -o "${DMG_NAME}"
          
          # SHA256を計算
          SHA256=$(shasum -a 256 "${DMG_NAME}" | cut -d' ' -f1)
          
          # Formulaディレクトリを作成
          mkdir -p Formula
          
          # Formulaを生成
          cat > Formula/mdc.rb << 'FORMULA'
class Mdc < Formula
  desc "MDC - Markdown Converter"
  homepage "https://github.com/zoetin45/mdc"
  version "VERSION_PLACEHOLDER"
  
  url "URL_PLACEHOLDER"
  sha256 "SHA256_PLACEHOLDER"

  def install
    app = "mdc.app"
    prefix.install Dir["*"]
    bin.install_symlink prefix/app/"Contents/MacOS/mdc"
  end
end
FORMULA
          
          # プレースホルダーを置換
          sed -i "s|VERSION_PLACEHOLDER|${VERSION}|g" Formula/mdc.rb
          sed -i "s|URL_PLACEHOLDER|${DMG_URL}|g" Formula/mdc.rb
          sed -i "s|SHA256_PLACEHOLDER|${SHA256}|g" Formula/mdc.rb
          
          # クリーンアップ
          rm -f "${DMG_NAME}"

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/mdc.rb
          git commit -m "Update to version ${{ steps.version.outputs.tag }}"
          git push
