name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag (e.g., v0.1.10)'
        required: true
        default: 'v0.1.10'

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
          fi
          
      - name: Checkout homebrew-tap
        uses: actions/checkout@v4
        with:
          repository: zoetin45/homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          
      - name: Update Formula
        run: |
          # バージョンを取得
          VERSION="${{ steps.version.outputs.tag }}"
          VERSION="${VERSION#v}"
          
          # DMGファイルの情報
          DMG_NAME="mdc_${VERSION}_universal.dmg"
          DMG_URL="https://github.com/zoetin45/mdc/releases/download/${{ steps.version.outputs.tag }}/${DMG_NAME}"
          
          # DMGをダウンロード
          curl -sL "${DMG_URL}" -o "${DMG_NAME}"
          
          # SHA256を計算
          SHA256=$(shasum -a 256 "${DMG_NAME}" | cut -d' ' -f1)
          
          # Formulaディレクトリを作成
          mkdir -p Formula
          
          # Formulaを生成（echoで1行ずつ）
          {
            echo 'class Mdc < Formula'
            echo '  desc "mdc - Just another markdown viewer"'
            echo '  homepage "https://github.com/zoetin45/mdc"'
            echo "  version \"${VERSION}\""
            echo "  url \"${DMG_URL}\""
            echo "  sha256 \"${SHA256}\""
            echo ''
            echo '  def install'
            echo '    # DMGをマウント'
            echo '    mountpoint = "/Volumes/mdc"'
            echo '    system "hdiutil", "attach", "-quiet", "-mountpoint", mountpoint, cached_download'
            echo ''
            echo '    begin'
            echo '      # アプリをインストール'
            echo '      app = Pathname.new("#{mountpoint}/mdc.app")'
            echo '      prefix.install app'
            echo ''
            echo '      # バイナリへのシンボリックリンクを作成'
            echo '      bin.install_symlink prefix/"mdc.app/Contents/MacOS/mdc"'
            echo '    ensure'
            echo '      # DMGをアンマウント'
            echo '      system "hdiutil", "detach", "-quiet", mountpoint'
            echo '    end'
            echo '  end'
            echo ''
            echo '  test do'
            echo '    system "#{bin}/mdc", "--version"'
            echo '  end'
            echo 'end'
          } > Formula/mdc.rb
          
          
          # 結果を確認
          echo "Generated Formula:"
          cat Formula/mdc.rb
          
          # クリーンアップ
          rm -f "${DMG_NAME}"

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/mdc.rb
          git commit -m "Update to version ${{ steps.version.outputs.tag }}"
          git push
